### ISSUE TITLE
Python 3 only: command line completion is broken when there are several matches

### ISSUE THREAD

**Issue by cvubrugier** [agrover/configshell-fb#17]
When targetcli-fb is built with Python 3, the command line completion does not display possible matches.

For instance, the following test case does not work:
* invoke targetcli (must be built for Python 3)
* hit the following key: "c"
* the following matches should be displayed: "cd" and "clearconfig"
* nothing is displayed

It turns out that there are two issues in `ConfigShell._display_completions()`:
1. The first issue is that some integer divisions are computed with the "/" operator whereas the "//" operator should be used.
2. The second issue is more subtle: at line 271, a variable called `len` is used but it is never assigned. As a consequence, what is accessed is the builtin `len()` function. It is incorrect and causes a type error with Python 3 but not with Python 2.7:

With Python 2.7:

    Python 2.7.10 (default, May 26 2015, 13:10:44) 
    >>> len > 0 and len < 1234567890
    False

With Python 3:

    Python 3.4.3+ (default, May  7 2015, 23:10:14) 
    >>> len > 0 and len < 1234567890
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    TypeError: unorderable types: builtin_function_or_method() > int()

I will provide patches for both issue. Moreover, I think the _display_completions() method is too complex and I would like to simplify it by removing the `completions_in_columns` option if you agree.

**Comment by agrover** [comment]
It appears completions_in_columns defaults to true. I'm fine with removing the option, but should we maybe keep the feature?

I'm guessing the code could be made more Pythonic using list chunking:

http://stackoverflow.com/questions/312443/how-do-you-split-a-list-into-evenly-sized-chunks-in-python

?

@tramjoe, thoughts?

**Comment by cvubrugier** [comment]
This bug was fixed some time last june:

> commit 2278675f79399a07dbe17415faae1af53d6f6974
> Merge: 33975c4 9587885
> Author: Andy Grover <andy@groveronline.com>
> Date:   Mon Jun 8 09:24:03 2015 -0700
> 
>     Merge pull request #18 from cvubrugier/fix-completion
>     
>     Fix the command line completion with Python 3 (issue #17)
