### ISSUE TITLE
Cannot autocomplete ipv6 portals

### ISSUE THREAD

**Issue by cvubrugier** [agrover/configshell-fb#20]
From the original bug report from @agrover: https://lists.fedorahosted.org/pipermail/targetcli-fb-devel/2015-November/000190.html

> We bracket iscsi ipv6 portals, so after creating one, it will show up in targetcli like
> 
> o- portals
>    o- [::]:3260
> 
> But, if I type "cd [<tab>" it doesn't autocomplete.

I will provide a fix.

**Comment by rldleblanc** [comment]
This doesn't fix all of the IPv6 issues. Please see Issue #34.
