### ISSUE TITLE
make rpm is failing for configshell-fb in RHEL 7.1

### ISSUE THREAD

**Issue by rlenkala** [agrover/configshell-fb#22]
Hi,

We are seeing error in compiling configshell-fb on RHEL 7.1. Most recently similar issue(https://github.com/agrover/rtslib-fb/issues/61) is resolved in rtslib-fb. I have done  code changes in configshell-fb and these code changes are made by referring the fix done as part of rtslib-fb(https://github.com/agrover/rtslib-fb/issues/61).
[make_configshell-fb_patch.txt](https://github.com/agrover/configshell-fb/files/203915/make_configshell-fb_patch.txt)

Could someone please find the attached patch and let me know your inputs on this?

Thanks,
Ravindar

**Comment by rlenkala** [comment]
Hi Andy,

Do you have few free mins to review the code changes mentioned above?

Thanks for your help on this!!

Regards,
-Ravindar

**Comment by agrover** [comment]
Sorry for the delay, I missed seeing this in my Github feed...

Thanks for your contribution! It looks fine.

Do you want to make a PR for these changes that I can merge, or would you like me to merge the patch manually?

**Comment by rlenkala** [comment]
Thanks for your review Andy!! 

Yes you can merge the patch manually.

-Ravindar

**Comment by agrover** [comment]
Merged. Thanks!
